# Generated by Django 5.0.3 on 2024-04-30 05:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institute_id', models.CharField(max_length=100, unique=True)),
                ('institute_name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='static/img/institute_img/%y', verbose_name='Profile Picture')),
                ('number_of_surveys', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('is_institute', 'Is Institute')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='groups_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.CharField(max_length=100)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.institute')),
            ],
            options={
                'unique_together': {('institute', 'groups')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.institute')),
            ],
            options={
                'permissions': [('is_student', 'Is Student')],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.CharField(max_length=100)),
                ('survey_description', models.CharField(default='', max_length=10000)),
                ('group', models.ManyToManyField(to='authuser.groups_table')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.institute')),
            ],
        ),
        migrations.CreateModel(
            name='student_responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.student')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.survey')),
            ],
        ),
        migrations.CreateModel(
            name='student_attending_survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.student')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.survey')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.survey'),
        ),
        migrations.CreateModel(
            name='SGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.groups_table')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.student')),
            ],
            options={
                'unique_together': {('student', 'group')},
            },
        ),
    ]
